[package]
name = "aws-c-builder-cmake"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bindgen.workspace = true
cmake.workspace = true
