[package]
name = "aws-c-iot-sys"
version = "0.1.0+v0.1.18"
links = "aws-c-iot"
publish.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-common-sys.workspace = true
aws-c-http-sys.workspace = true
aws-c-io-sys.workspace = true
aws-c-mqtt-sys.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
