[package]
name = "aws-c-common-sys"
version = "0.1.0+v0.9.10"
links = "aws-c-common"
publish.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
