[package]
name = "aws-c-io-sys"
version = "0.1.0+v0.13.35"
links = "aws-c-io"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-cal-sys.workspace = true
aws-c-common-sys.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
