[package]
name = "aws-c-mqtt-sys"
version = "0.1.0+v0.10.0"
links = "aws-c-mqtt"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-http-sys.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
