[package]
name = "s2n-tls-sys"
version = "0.1.0+v1.4.0"
links = "s2n"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.aws-c-builder]
repo = "https://github.com/aws/s2n-tls.git"

[dependencies]
aws-lc-sys.workspace = true
libc.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
