[package]
name = "s2n-tls-sys"
version = "0.1.0+v1.4.0"
links = "s2n-tls"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[package.metadata.aws-c-builder]
repo = "https://github.com/aws/s2n-tls.git"

[dependencies]

[build-dependencies]
aws-c-builder.workspace = true
