[package]
name = "aws-crt-cpp-sys"
version = "0.1.0+v0.24.9"
links = "aws-crt-cpp"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
openssl-sys.workspace = true

[build-dependencies]
cmake.workspace = true
