[package]
name = "aws-crt-cpp-sys"
version = "0.1.0+v0.24.9"
links = "aws-crt-cpp"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]

[target.'cfg(windows)'.dependencies]
schannel = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2"

[build-dependencies]
cmake.workspace = true
