[package]
name = "aws-iot-device-sdk-sys"
version = "0.1.0+v1.30.3"
# links = "aws-iot-device-sdk-cpp-v2"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]

[build-dependencies]
