[package]
name = "aws-iot-device-sdk-cpp-sys"
version = "0.1.0+v1.31.0"
links = "aws-iot-device-sdk-cpp-v2"
publish.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-iot-sys.workspace= true
aws-crt-cpp-sys.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
