[package]
name = "aws-lc-sys"
version = "0.1.0+v1.18.0"
links = "aws-lc"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.aws-c-builder]
repo = "https://github.com/aws/aws-lc.git"

[dependencies]
libc.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
