[package]
name = "aws-c-cal-sys"
version = "0.1.0+v0.6.9"
links = "aws-c-cal"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-common-sys.workspace = true

[target.'cfg(windows)'.dependencies]
schannel = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
aws-lc-sys.workspace = true

[build-dependencies]
aws-c-builder.workspace = true
