[package]
name = "aws-c-cal-sys"
version = "0.1.0+v0.6.9"
links = "aws-c-cal"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
aws-c-common-sys.workspace = true

[build-dependencies]
cmake.workspace = true
